#!/bin/bash
# /etc/init.d/piEnergy

### BEGIN INIT INFO
# Provides:          piEnergy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: logging energy usage
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting piEnergy"
        /home/pi/piEnergy/piEnergy&
        ;;
    stop)
        echo "Stopping piEnergy"
        killall piEnergy
        ;;
    *)
        echo "Usage: /etc/init.d/piEnergy start|stop"
        exit 1
        ;;
esac

exit 0
